// auto-generated
// Code generated by Defyne GUI builder.

package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

type gui struct {
	txtPlain  *widget.Entry
	txtKey    *widget.Entry
	txtResult *widget.Entry
}

func newGUI() *gui {
	return &gui{}
}

func (g *gui) makeUI() fyne.CanvasObject {
	g.txtResult = &widget.Entry{Text: "", PlaceHolder: "this is result ! "}
	g.txtPlain = &widget.Entry{Text: "", PlaceHolder: "please intput plain ..."}
	g.txtKey = &widget.Entry{Text: "", PlaceHolder: "please input key ..."}

	return container.NewVBox(
		widget.NewLabel("plain"),
		g.txtPlain,
		widget.NewLabel("key"),
		g.txtKey,
		widget.NewLabel("cipher"),
		g.txtResult,
		widget.NewButtonWithIcon("encrypt", theme.ConfirmIcon(), func() {}),
		widget.NewButtonWithIcon("decrypt", theme.CancelIcon(), func() {}),
		widget.NewButtonWithIcon("exit", theme.DeleteIcon(), func() {}))
}
